electrode-io/electrode-ota-server

- README.md
- electrode-ota-server-dao-cassandra/package.json
- electrode-ota-server-dao-cassandra/yarn.lock
- electrode-ota-server-default-config/src/index.js
- electrode-ota-server-model-acquisition/src/acquisition.js
- electrode-ota-server-model-app/src/app.js
- electrode-ota-server-model-app/test/app-test.js
- electrode-ota-server-model-manifest/src/manifest.js
- lerna.json
- fix for hotcodepush.json; it kept having an array with numbers 1-10000, and the client device was attempting to delete files with names 1-10000 upon install of the update.  Found that the manifest variable getting passed to the delta() function was a buffer instead of an object. Added code to convert it if this was the case.
- updated express-cassandra version to get around a bug with that lib
- fix for an issue in the issues list where the updateCheck was always returning true
- added default config of 90MB for uploads
- fix for installed update always showing previous update's content.  Found that the way genDiffPackageMap was calling delta() caused the currently installed zip to get traversed and its content was added to the diff zip.  The latest package's zip content needs to get …
> Mostly bug fixes

- electrode-ota-server-model-app/src/app.js
- electrode-ota-server-model-app/test/app-test.js
Say we have v1 and v2 deployments, and wish to roll back to v1.
Previously when running
```
code-push rollback code-push rollback <appName> <deploymentName> -r v1
```
it would roll back to v1 appropriately, but when viewing deployment history on v3 it would say
```
(Rolled back v2 to v2)
```
This was because `dpkg.label` is the newer version number (v2).  By replacing it with `params.label` (the input to -r) history now will properly say
```
(Rolled back v2 to v1)
```
> Fix rolled back version

- README.md
- example-with-ui/config/development.json
- Some quotes in the readme not accurate
- Fix incorrect plugin name in example development.json 
This may close issue #13
> Fix typos based on current package structure

- electrode-ota-server-model-app/src/app.js
- electrode-ota-server-model-app/test/app-test.js
In the recent package hash refactoring, missed a location that was using the old hashing method.
Use async for upload()
> Fix duplicate package detection

- electrode-ota-ui/webpack.config.js
Use of the --hot flag already adds HotModuleReplacementPlugin.   Adding it again will cause issues.
> --hot flag already adds HotModuleReplacementPlugin

- electrode-ota-server-fileservice-download/src/index.js
- electrode-ota-server-model-acquisition/test/acquisition-test.js
- electrode-ota-server-model-app/src/app.js
- electrode-ota-server-model-app/src/index.js
- electrode-ota-server-model-app/test/app-test.js
- electrode-ota-server-model-manifest/src/manifest.js
- electrode-ota-server-routes-acquisition/src/index.js
- electrode-ota-server-service-fileservice/src/index.js
Because of the need to return the Content-Length header, we need a download's content and length.  Update service-download to return length and content.
Remove reference to service-download from  electrode-ota-server-service-fileservice,  electrode-ota-server-model-app.  Not needed in those projects.
> update download() function to return content and length.

- electrode-ota-server-model-acquisition/src/acquisition.js
- electrode-ota-server-model-acquisition/test/acquisition-test.js
If the client version is higher than the available package, then return no update available.
> if client version is higher, then no update available

- electrode-ota-ui/src/pages/Deployment/index.js
Fix issue where UI was only showing Production metrics, even if you are on the Staging view.  It was because it was not passing the environment (`value` field) to the server call.
> Fix UI metric for staging

- electrode-ota-server-model-app/src/app.js
- electrode-ota-server-model-app/test/app-test.js
code-push patch was using the latest version when updating an older package.  this fix is to ensure it uses the correct version if a label is specified.
> fix patch to update from appropriate version

- electrode-ota-mariadb-schema/sql-tests/run-tests.sh
Add a little delay (5 secs) before running the database tests, to make sure that the database tables have been properly created.
Without doing this, running the `test.sh` script from [electrode-ota-maria-db](https://github.com/electrode-io/electrode-ota-server/tree/master/electrode-ota-mariadb-schema) fails consistently on my workstation (see logs below).
Seems like the tests are immediately started once the `ota-db` container is reachable and at this point, the tables are now fully created yet.
There is probably a better solution, but this one does the job in a simple way. 
```
$ ./test.sh
Building ota-db
Step 1/1 : FROM mariadb:10.3
---> f0b6a295092e
Successfully built f0b6a295092e
Successfully tagged electrodeotamariadbschema_ota-db:latest
Building liquibase
Step 1/2 : FROM …
```
> Delay SQL tests run to give time for db tables creation

- electrode-ota-server-model-app/src/app.js
- electrode-ota-server-model-app/test/app-test.js
Allow a bundle to be promoted with the same hash, only if the AppVersion is different.
> allow promotion of same bundle to different app versions

- electrode-ota-ui/src/pages/Deployment/index.js
fix bug: If the rollout is 100%, it doesn't get updated.
> fix ui bugs with update to 100% rollout

- electrode-ota-server-dao-mariadb/src/ElectrodeOtaDaoRdbms.ts
- electrode-ota-server-dao-mariadb/src/IElectrodeOtaDao.ts
- electrode-ota-server-dao-mariadb/src/dao/PackageDAO.ts
- electrode-ota-server-dao-mariadb/src/queries/PackageQueries.ts
- electrode-ota-server-dao-mariadb/test/ElectrodeOtaDaoRdms-spec.ts
- electrode-ota-server-dao-plugin/src/dao.js
- electrode-ota-server-dao-plugin/test/dao-cassandra-test.js
- electrode-ota-server-model-acquisition/src/acquisition.js
- electrode-ota-server-model-acquisition/test/acquisition-test.js
Given two binary versions, with the same bundle IDs.
Version v1.1.0 . bundleHash ABC . label v1
Version v1.2.0 . bundleHash ABC . label v2
A new bundle is released to both binary versions
Version v1.1.0 . bundleHash DEF . label v3
Version v1.2.0 . bundleHash DEF . label v4
When mobile clients on version v1.1.0 check for updates..
Expected: return package label v3.
Actual: returns "update not available".  this is because we don't search using the appVersion.
> On updateCheck, find latest package that matches specified appVersion

- package.json
Allow Node.js versions **greater than or equal** to `8.16`, instead of only `^8.16.0`.
Node.js 8 will reach [end of life in December 2019](https://nodejs.org/en/about/releases/).
The **active LTS** versions are Node.js 10 and Node.js 12, and the current version is Node.js 13. Unless there are strong reasons, we should not artificially restrict this project to a Node version that will soon be obsolete.
> Relax node engine restriction

- package.json
- yarn.lock
The `lint` script in the project fails with the error below. This PR adds the missing `eslint-plugin-mocha` entry to `devDependencies`.
```
$ ./node_modules/.bin/eslint ./**/*.js
Oops! Something went wrong! :(
ESLint: 4.19.1.
ESLint couldn't find the plugin "eslint-plugin-mocha". This can happen for a couple different reasons:
1. If ESLint is installed globally, then make sure eslint-plugin-mocha is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.
2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
npm i eslint-plugin-mocha@latest --save-dev
If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
error …
```
> Add missing eslint-plugin-mocha

- electrode-ota-server-model-acquisition/src/acquisition.js
- electrode-ota-server-routes-acquisition/src/index.js
- electrode-ota-server-routes-acquisition/src/keys-to-camel-or-snake.js
- electrode-ota-server-routes-acquisition/src/to-camel-case.js
- electrode-ota-server-routes-acquisition/src/to-snake-case.js
- electrode-ota-server/test/electrode-ota-server-test.js
CodePush definition update for the new Service
source: https://github.com/microsoft/code-push/pull/645/files
The changes here responds to new `/update_check`, `/report_status/deploy`, `/report_status/download` services, all with new set of parameters(modified the queries to camelCase to snake_case).
Still the existing `/updateCheck`, `/reportStatus/deploy`, `/reportStatus/download` services are supported as well.
> CodePush definition update changes in Electrode OTA Server

- electrode-ota-server-model-app/src/app.js
- electrode-ota-server-model-app/test/app-test.js
- electrode-ota-server-routes-apps/src/index.js
- electrode-ota-server-routes-auth/src/index.js
- package.json
When deploying a new app, they NEED real-time data to monitor for bad versions.  This usually occurs in the first 10 minutes or so.
Taking  the summation of the last time it's summed, query the database for the remaining real-time data. This query should be quick because it is time-bound. 
If the last summed time is > than 1 day, query only for 1 day's worth of data.
> add real-time data to metrics-summary

- electrode-ota-server-routes-acquisition/src/index.js
`/foo_getp/{hash}` sends standard cache-control header to enable caching in proxy(Edgecast)
It's a temporary api to validate the caching.
It's not exposed anywhere.
Existing `/storagev2/{hash}` will not send any cache-control headers.
> temp api to download packages to validate proxy cache

- electrode-ota-server-dao-mariadb/src/ElectrodeOtaDaoRdbms.ts
- electrode-ota-server-dao-mariadb/src/dao/MetricDAO.ts
- electrode-ota-server-dao-mariadb/src/queries/MetricQueries.ts
- electrode-ota-server-dao-mariadb/test/ElectrodeOtaDaoRdms-spec.ts
- electrode-ota-server-model-app/src/app.js
- electrode-ota-server-model-app/src/index.js
- electrode-ota-server-model-app/test/app-test.js
retrieving real-time metrics by time range fails if used timestamp
1. converting `create_time` to timestamp using `UNIX_TIMESTAMP()` in each record takes more time.
2. simple date comparison `create_time >= '2020-04-20 19:01:00'` yields results.
added ccm config(`doRealTimeMetrics`) to control real-time data fetch, so that it can be turned off if not required.
> fix real-time metrics query and add ccm to control it

- electrode-ota-server-routes-acquisition/src/handlers.js
There're certain CDNs that require `max-age`
Ref: https://jira.walmart.com/browse/BFDTORBIT-19954
> Set max-age for caching
